# Generated by Django 5.1.1 on 2024-09-10 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('votacao', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pergunta',
            name='imagem',
            field=models.ImageField(default='', upload_to='uploads/'),
        ),
    ]
