# Generated by Django 5.1.2 on 2024-10-22 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_comentario'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='imagem',
            field=models.ImageField(default='', upload_to='uploads/'),
        ),
    ]
